package rules

import (
	"github.com/bouncerfox/cli/pkg/document"
)

// allFileTypes lists every supported file type.
var allFileTypes = []string{
	document.FileTypeSkillMD,
	document.FileTypeClaudeMD,
	document.FileTypeAgentMD,
	document.FileTypeSettingsJSON,
	document.FileTypeMCPJSON,
	document.FileTypeRulesMD,
	document.FileTypePluginJSON,
	document.FileTypeHooksJSON,
	document.FileTypeLSPJSON,
	document.FileTypeCursorRules,
	document.FileTypeWindsurfRules,
	document.FileTypeCopilotMD,
	document.FileTypeAgentsMD,
}

// mdFileTypes lists all markdown-based file types.
var mdFileTypes = []string{
	document.FileTypeSkillMD,
	document.FileTypeClaudeMD,
	document.FileTypeAgentMD,
	document.FileTypeRulesMD,
	document.FileTypeCursorRules,
	document.FileTypeWindsurfRules,
	document.FileTypeCopilotMD,
	document.FileTypeAgentsMD,
}

// jsonFileTypes lists all JSON-based file types.
var jsonFileTypes = []string{
	document.FileTypeSettingsJSON,
	document.FileTypeMCPJSON,
	document.FileTypePluginJSON,
	document.FileTypeHooksJSON,
	document.FileTypeLSPJSON,
}

// execFileTypes lists JSON file types that contain executable commands.
var execFileTypes = []string{
	document.FileTypeSettingsJSON,
	document.FileTypeMCPJSON,
	document.FileTypeHooksJSON,
	document.FileTypeLSPJSON,
}

// Registry is an ordered slice of all rules. SEC_001 must appear first so
// that it caches line numbers before SEC_006 and SEC_018 consume that cache.
var Registry = []document.RuleMetadata{
	// ── Security ────────────────────────────────────────────────────────
	{
		ID:               "SEC_001",
		Name:             "Hardcoded Secret",
		Category:         "security",
		Description:      "API keys, tokens, or credentials embedded directly in file content",
		Remediation:      "Remove hardcoded secrets and use environment variables or a secret manager.",
		DefaultSeverity:  document.SeverityCritical,
		DefaultFileTypes: allFileTypes,
		Check:            CheckSEC001,
	},
	{
		ID:               "SEC_002",
		Name:             "External URL",
		Category:         "security",
		Description:      "URL pointing to a domain not in the organization's allowlist",
		Remediation:      "Verify this URL is in the organization's allowlist, or remove it.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: allFileTypes,
		Check:            CheckSEC002,
	},
	{
		ID:               "SEC_003",
		Name:             "Destructive Command",
		Category:         "security",
		Description:      "File deletion or destructive shell command in a skill definition",
		Remediation:      "Remove destructive file operations from skill definitions.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: []string{document.FileTypeSkillMD},
		Check:            CheckSEC003,
	},
	{
		ID:               "SEC_004",
		Name:             "Invisible Unicode",
		Category:         "security",
		Description:      "Zero-width or invisible characters that can hide malicious instructions",
		Remediation:      "Remove invisible unicode characters that could be used for instruction smuggling.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: mdFileTypes,
		Check:            CheckSEC004,
	},
	{
		ID:               "SEC_006",
		Name:             "Base64 Blob",
		Category:         "security",
		Description:      "Base64-encoded content that may conceal secrets or payloads",
		Remediation:      "Review the base64-encoded content to ensure it does not contain secrets or malicious payloads.",
		DefaultSeverity:  document.SeverityWarn,
		DefaultFileTypes: allFileTypes,
		Check:            CheckSEC006,
	},
	{
		ID:               "SEC_007",
		Name:             "Data URI",
		Category:         "security",
		Description:      "data: URI that can embed executable or obfuscated content",
		Remediation:      "Remove data: URIs — they can embed malicious payloads.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: allFileTypes,
		Check:            CheckSEC007,
	},
	{
		ID:               "SEC_009",
		Name:             "Reverse Shell in Hook",
		Category:         "security",
		Description:      "Hook command opens a reverse shell connection",
		Remediation:      "Remove the reverse shell command from hook configuration.",
		DefaultSeverity:  document.SeverityCritical,
		DefaultFileTypes: execFileTypes,
		Check:            CheckSEC009,
	},
	{
		ID:               "SEC_010",
		Name:             "Credential Exfiltration in Hook",
		Category:         "security",
		Description:      "Hook command accesses and exfiltrates environment variables or credentials",
		Remediation:      "Remove credential access from hook commands.",
		DefaultSeverity:  document.SeverityCritical,
		DefaultFileTypes: execFileTypes,
		Check:            CheckSEC010,
	},
	{
		ID:               "SEC_011",
		Name:             "Download and Execute",
		Category:         "security",
		Description:      "Command downloads and immediately executes remote content",
		Remediation:      "Remove download-and-execute patterns from commands.",
		DefaultSeverity:  document.SeverityCritical,
		DefaultFileTypes: execFileTypes,
		Check:            CheckSEC011,
	},
	{
		ID:               "SEC_012",
		Name:             "Dangerous Env Var",
		Category:         "security",
		Description:      "Environment variable override that can hijack proxy, path, or library loading",
		Remediation:      "Remove dangerous environment variable overrides.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: execFileTypes,
		Check:            CheckSEC012,
	},
	{
		ID:               "SEC_014",
		Name:             "Unpinned MCP Package",
		Category:         "security",
		Description:      "MCP server uses an unpinned package version, introducing supply chain risk",
		Remediation:      "Pin the MCP package to a specific version.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: []string{document.FileTypeMCPJSON, document.FileTypeLSPJSON},
		Check:            CheckSEC014,
	},
	{
		ID:               "SEC_016",
		Name:             "Plain HTTP MCP Server",
		Category:         "security",
		Description:      "MCP server URL uses plain HTTP instead of HTTPS",
		Remediation:      "Use HTTPS for MCP server URLs.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: []string{document.FileTypeMCPJSON},
		Check:            CheckSEC016,
	},
	{
		ID:               "SEC_018",
		Name:             "High-Entropy Secret",
		Category:         "security",
		Description:      "High-entropy string in a credential context that may be a hardcoded secret",
		Remediation:      "If this is a secret, remove it and use environment variables or a secret manager. If it is a hash or identifier, it can be safely ignored.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: allFileTypes,
		Check:            CheckSEC018,
	},
	{
		ID:               "SEC_019",
		Name:             "YAML Anchor/Alias",
		Category:         "security",
		Description:      "YAML anchor or alias in frontmatter — potential YAML bomb",
		Remediation:      "Remove YAML anchors (&) and aliases (*) from frontmatter.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: []string{document.FileTypeSkillMD, document.FileTypeAgentMD, document.FileTypeRulesMD},
		Check:            CheckSEC019,
	},
	{
		ID:               "SEC_020",
		Name:             "Deeply Nested JSON",
		Category:         "security",
		Description:      "JSON nesting exceeds maximum depth — possible resource exhaustion",
		Remediation:      "Reduce JSON nesting depth to 10 levels or fewer.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: jsonFileTypes,
		Check:            CheckSEC020,
	},
	// ── Quality ─────────────────────────────────────────────────────────
	{
		ID:               "QA_001",
		Name:             "Missing Description",
		Category:         "quality",
		Description:      "No description field in frontmatter — Claude cannot auto-invoke this skill",
		Remediation:      "Add a description field to the skill's frontmatter.",
		DefaultSeverity:  document.SeverityWarn,
		DefaultFileTypes: []string{document.FileTypeSkillMD},
		Check:            CheckQA001,
	},
	{
		ID:               "QA_002",
		Name:             "Name Mismatch",
		Category:         "quality",
		Description:      "Frontmatter name does not match the skill's directory name",
		Remediation:      "Update the name to match the directory name.",
		DefaultSeverity:  document.SeverityWarn,
		DefaultFileTypes: []string{document.FileTypeSkillMD},
		Check:            CheckQA002,
	},
	{
		ID:               "QA_003",
		Name:             "Short Description",
		Category:         "quality",
		Description:      "Description too brief for Claude to reliably determine when to invoke",
		Remediation:      "Write a more detailed description (minimum 20 characters).",
		DefaultSeverity:  document.SeverityWarn,
		DefaultFileTypes: []string{document.FileTypeSkillMD},
		Check:            CheckQA003,
	},
	{
		ID:               "QA_004",
		Name:             "Empty Body",
		Category:         "quality",
		Description:      "Skill body is empty — no instructions for the agent",
		Remediation:      "Add instructions to the skill body.",
		DefaultSeverity:  document.SeverityWarn,
		DefaultFileTypes: []string{document.FileTypeSkillMD},
		Check:            CheckQA004,
	},
	{
		ID:               "QA_005",
		Name:             "Thin Skill Body",
		Category:         "quality",
		Description:      "Skill body is too short after stripping code blocks — insufficient prose instructions",
		Remediation:      "Add more prose instructions to the skill body.",
		DefaultSeverity:  document.SeverityInfo,
		DefaultFileTypes: []string{document.FileTypeSkillMD},
		Check:            CheckQA005,
	},
	{
		ID:               "QA_006",
		Name:             "Missing Tools List",
		Category:         "quality",
		Description:      "No tools list in frontmatter — skill does not declare which tools it uses",
		Remediation:      "Add a 'tools' list to the frontmatter to declare which tools this skill uses.",
		DefaultSeverity:  document.SeverityInfo,
		DefaultFileTypes: []string{document.FileTypeSkillMD},
		Check:            CheckQA006,
	},
	{
		ID:               "QA_007",
		Name:             "Invalid Name Format",
		Category:         "quality",
		Description:      "Name exceeds 64 characters or contains characters other than lowercase, numbers, and hyphens",
		Remediation:      "Use lowercase letters, numbers, and hyphens only (max 64 chars).",
		DefaultSeverity:  document.SeverityWarn,
		DefaultFileTypes: []string{document.FileTypeSkillMD},
		Check:            CheckQA007,
	},
	{
		ID:               "QA_008",
		Name:             "Oversized File",
		Category:         "quality",
		Description:      "File exceeds 50KB, which may degrade Claude's context performance",
		Remediation:      "Reduce file size below 50KB.",
		DefaultSeverity:  document.SeverityWarn,
		DefaultFileTypes: allFileTypes,
		Check:            CheckQA008,
	},
	{
		ID:               "QA_009",
		Name:             "Max Scannable Size",
		Category:         "quality",
		Description:      "File exceeds maximum scannable size and was only partially analyzed",
		Remediation:      "Reduce file size or split into smaller files.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: allFileTypes,
		Check:            CheckQA009,
	},
	{
		ID:               "QA_010",
		Name:             "Binary File",
		Category:         "quality",
		Description:      "File contains binary content and cannot be scanned as text",
		Remediation:      "Replace binary content with text or exclude from scan.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: allFileTypes,
		Check:            CheckQA010,
	},
	// ── Config ──────────────────────────────────────────────────────────
	{
		ID:               "CFG_001",
		Name:             "Unrestricted Bash",
		Category:         "config",
		Description:      "Bash tool granted with no command restrictions",
		Remediation:      "Restrict bash tool with explicit command patterns.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: []string{document.FileTypeSettingsJSON},
		Check:            CheckCFG001,
	},
	{
		ID:               "CFG_002",
		Name:             "Unrestricted Write",
		Category:         "config",
		Description:      "Write tool granted with no path restrictions",
		Remediation:      "Restrict Write tool to specific file paths.",
		DefaultSeverity:  document.SeverityWarn,
		DefaultFileTypes: []string{document.FileTypeSettingsJSON},
		Check:            CheckCFG002,
	},
	{
		ID:               "CFG_003",
		Name:             "MCP Wildcard Permission",
		Category:         "config",
		Description:      "Wildcard MCP pattern grants access to all tools of a server",
		Remediation:      "Specify exact MCP tool names instead of wildcards.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: []string{document.FileTypeSettingsJSON},
		Check:            CheckCFG003,
	},
	{
		ID:               "CFG_004",
		Name:             "Shell Injection in Hook",
		Category:         "config",
		Description:      "Hook command contains shell metacharacters that risk injection",
		Remediation:      "Avoid shell metacharacters in hook commands; use explicit argument lists.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: execFileTypes,
		Check:            CheckCFG004,
	},
	{
		ID:               "CFG_005",
		Name:             "Too Many Allowed Tools",
		Category:         "config",
		Description:      "allowedTools list exceeds 20 entries — overly broad permissions",
		Remediation:      "Reduce the number of allowed tools to the minimum required.",
		DefaultSeverity:  document.SeverityInfo,
		DefaultFileTypes: []string{document.FileTypeSettingsJSON},
		Check:            CheckCFG005,
	},
	{
		ID:               "CFG_006",
		Name:             "No Denied Tools",
		Category:         "config",
		Description:      "No deniedTools key present — consider explicitly blocking dangerous tools",
		Remediation:      "Add a 'deniedTools' list to explicitly block dangerous tools.",
		DefaultSeverity:  document.SeverityInfo,
		DefaultFileTypes: []string{document.FileTypeSettingsJSON},
		Check:            CheckCFG006,
	},
	{
		ID:               "CFG_007",
		Name:             "Hook Defined",
		Category:         "config",
		Description:      "Hooks are defined — all hooks require reviewer acknowledgment",
		Remediation:      "Ensure all hooks are reviewed and acknowledged.",
		DefaultSeverity:  document.SeverityInfo,
		DefaultFileTypes: []string{document.FileTypeSettingsJSON},
		Check:            CheckCFG007,
	},
	{
		ID:               "CFG_009",
		Name:             "Broad MCP Permission Flag",
		Category:         "config",
		Description:      "MCP server or hook uses broad permission flags like --allow-all or --no-sandbox",
		Remediation:      "Remove broad permission flags and grant specific permissions only.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: []string{document.FileTypeSettingsJSON, document.FileTypeMCPJSON, document.FileTypeHooksJSON, document.FileTypeLSPJSON},
		Check:            CheckCFG009,
	},
	{
		ID:               "SEC_021",
		Name:             "Dangerous Import Reference",
		Category:         "security",
		Description:      "File imports content from a path that traverses upward, uses an absolute path, or targets known sensitive locations",
		Remediation:      "Remove the dangerous import. Do not import files outside the project directory or from sensitive locations.",
		DefaultSeverity:  document.SeverityHigh,
		DefaultFileTypes: mdFileTypes,
		Check:            CheckSEC021,
	},
	// ── Prompt Safety ───────────────────────────────────────────────────
	{
		ID:               "PS_004",
		Name:             "Hidden HTML Comment",
		Category:         "prompt-safety",
		Description:      "HTML comment containing instructions not visible when rendered",
		Remediation:      "Remove or shorten hidden HTML comments containing instructions.",
		DefaultSeverity:  document.SeverityWarn,
		DefaultFileTypes: mdFileTypes,
		Check:            CheckPS004,
	},
}
